version: '3'

services:
    weather:
        build: .
        image: weather
        container_name: weather
        env_file:
            - config.env
        environment:
            - VIRTUAL_HOST=weather.jahiduls.io

networks:
    default:
        external:
           name: nginx-network

